const app=document.querySelector('#app'),grid=document.querySelector('#grid'),fmt=n=>'$'+Number(n||0).toLocaleString('pt-BR');let state=null,selected=null,selectedColor=1,previewActive=false,view='stock',order={};
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2500)}
function updatePreviewButton(){const button=document.querySelector('#previewBtn');button.textContent=previewActive?'Remover previa':'Exibir previa';button.classList.toggle('danger',previewActive);button.disabled=!selected&&!previewActive}
function setColor(color,apply=true){selectedColor=Number(color)||1;document.querySelectorAll('.color').forEach(x=>x.classList.toggle('active',Number(x.dataset.color)===selectedColor));if(apply&&selected)post('previewColor',{color:selectedColor})}
function resetSelection(hasPreview=false){selected=null;previewActive=hasPreview;setColor(1,false);document.querySelector('#detailName').textContent='Selecione um veiculo';document.querySelector('#detailBrand').textContent='';document.querySelector('#detailPrice').textContent='';document.querySelector('#detailStock').textContent='0';document.querySelector('#detailModel').textContent='-';document.querySelector('#sellBtn').disabled=true;updatePreviewButton()}
function select(v){selected=v;previewActive=false;setColor(1,false);document.querySelectorAll('.card').forEach(x=>x.classList.toggle('active',x.dataset.model===v.model));document.querySelector('#detailName').textContent=v.label;document.querySelector('#detailBrand').textContent=v.brand;document.querySelector('#detailPrice').textContent=fmt(v.price);document.querySelector('#detailStock').textContent=v.stock;document.querySelector('#detailModel').textContent=v.model;document.querySelector('#sellBtn').disabled=v.stock<1;updatePreviewButton();post('selectVehicle',{model:v.model,color:selectedColor})}
function render(){const q=document.querySelector('#search').value.toLowerCase(),list=state.vehicles.filter(v=>v.stock>0&&(v.label+' '+v.brand).toLowerCase().includes(q));grid.innerHTML='';list.forEach(v=>{const b=document.createElement('button');b.className='card';b.dataset.model=v.model;b.classList.toggle('active',selected&&selected.model===v.model);b.innerHTML=`<span class="category">${v.category}</span><h3>${v.label}</h3><p>${v.brand}</p><footer><span>${fmt(v.price)}</span><span>${v.stock} un.</span></footer>`;b.onclick=()=>select(v);grid.appendChild(b)});if(!list.length)grid.innerHTML='<small>Nenhum veiculo disponivel no estoque.</small>';document.querySelector('#count').textContent=`${list.length} veiculos encontrados`}
function renderOrder(){const box=document.querySelector('#orderLines'),available=state.vehicles.filter(v=>v.canOrder);box.innerHTML='';available.forEach(v=>{const row=document.createElement('div');row.className='invoice-row';row.innerHTML=`<span><b>${v.label}</b><small>${fmt(v.cost)} por unidade</small></span><input type="number" min="0" max="10" value="${order[v.model]||0}"><strong>${fmt((order[v.model]||0)*v.cost)}</strong>`;row.querySelector('input').oninput=e=>{order[v.model]=Math.max(0,Math.floor(+e.target.value||0));renderOrder()};box.appendChild(row)});if(!available.length)box.innerHTML='<small>Nenhuma categoria habilitada para compra.</small>';const total=available.reduce((s,v)=>s+(order[v.model]||0)*v.cost,0),units=available.reduce((s,v)=>s+(order[v.model]||0),0);document.querySelector('#orderTotal').textContent=fmt(total);document.querySelector('#confirmOrder').disabled=!units||units>10}
function setView(v){view=v;document.querySelector('#stockView').classList.toggle('hidden',v!=='stock');document.querySelector('#orderView').classList.toggle('hidden',v!=='order');document.querySelector('#detail').classList.toggle('hidden',v!=='stock');document.querySelector('#title').textContent=v==='stock'?'Veiculos em estoque':'Pedido de reposicao';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===v));if(v==='order')renderOrder()}
window.addEventListener('message',e=>{if(e.data.action==='open'){state=e.data.data;resetSelection(e.data.previewActive===true);app.classList.remove('hidden');document.querySelector('#brand').textContent=state.label;document.querySelector('#invoiceUnit').textContent=state.label;document.querySelector('#balance').textContent=fmt(state.balance);setView('stock');render()}if(e.data.action==='close')app.classList.add('hidden')});
document.querySelector('#search').oninput=render;document.querySelector('#close').onclick=()=>{app.classList.add('hidden');post('close')};document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>setView(n.dataset.view));document.querySelector('#previewBtn').onclick=async()=>{if(previewActive){await post('removePreview');previewActive=false;updatePreviewButton();return}if(!selected)return;await post('preview',{model:selected.model,color:selectedColor});previewActive=true;updatePreviewButton()};
document.querySelectorAll('.color').forEach(button=>button.onclick=()=>setColor(button.dataset.color));
document.querySelector('#sellBtn').onclick=async()=>{if(!selected)return;const players=await post('nearby'),list=document.querySelector('#playerList'),modal=document.querySelector('#players');list.innerHTML='';if(!players.length){toast('Nenhum jogador proximo.');return}players.forEach(p=>{const b=document.createElement('button');b.className='player';b.textContent=`${p.name} (ID ${p.id})`;b.onclick=async()=>{const r=await post('sell',{model:selected.model,target:p.id,color:selectedColor});modal.close();if(r.ok){selected.stock--;render();select(selected);toast('Venda concluida.')}else toast(r.error)}});modal.showModal()};
document.querySelector('#confirmOrder').onclick=async()=>{const r=await post('order',{items:order});if(r.ok)toast(`Pedido pago: ${r.invoice}`);else toast(r.error||'Pedido recusado.')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){app.classList.add('hidden');post('close')}});
