const state={project:null,recipes:[],inventory:[],outputs:[],recipe:null,imagePath:'',busy:false,progressTimer:null,placed:new Set()};
const $=id=>document.getElementById(id);
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
const image=name=>`${state.imagePath}${name}.png`;
const amount=name=>state.inventory.filter(i=>i.name===name).reduce((n,i)=>n+i.count,0);
const quantity=()=>Math.max(1,Math.min(Number($('quantity').dataset.max)||50,Math.floor(Number($('quantity').value)||1)));
const required=ingredient=>ingredient.tool&&state.inventory.some(i=>i.name===ingredient.name&&i.hasDurability)?1:ingredient.count*quantity();
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function esc(v){const e=document.createElement('span');e.textContent=v??'';return e.innerHTML}
function renderOutputs(){const query=$('outputSearch').value.toLowerCase();const visible=state.outputs.filter(o=>(o.label+' '+o.item).toLowerCase().includes(query));const box=$('outputs');box.innerHTML=visible.map(o=>`<div class="output-card"><img src="${image(o.item)}"><div><strong>${esc(o.label)}</strong><small>${esc(o.createdAt||'Pronto')} • 1 unidade</small></div><button data-output="${o.id}">Pegar item</button></div>`).join('')||`<div class="empty-output">${state.outputs.length?'Nenhum item encontrado.':'Nenhum item pronto.'}</div>`;box.querySelectorAll('[data-output]').forEach(b=>b.onclick=()=>takeOutput(Number(b.dataset.output)));$('takeAll').disabled=!state.outputs.length||state.busy}
function usableInventory(filter=''){if(!state.recipe)return[];const names=new Set(state.recipe.ingredients.map(i=>i.name));return state.inventory.filter(i=>names.has(i.name)&&(i.label+' '+i.name).toLowerCase().includes(filter.toLowerCase()))}
function placeIngredient(item){const ingredient=state.recipe?.ingredients.find(x=>x.name===item),slot=[...document.querySelectorAll('.slot')].find(el=>el.dataset.item===item);if(!ingredient||!slot)return;if(amount(item)<required(ingredient))return toast('Quantidade insuficiente.');state.placed.add(item);slot.classList.remove('missing','dragover','insufficient');slot.classList.add('ok','filled');slot.querySelector('small').textContent=`${required(ingredient)}x posicionado`;slot.querySelector('b').textContent=`${required(ingredient)}x`;slot.querySelector('b').classList.remove('hidden');slot.querySelector('.remove-slot').classList.remove('hidden');updateAssembly()}
function startManualDrag(event,source){if(event.button!==0||state.busy)return;event.preventDefault();const item=source.dataset.item,ghost=source.querySelector('img').cloneNode(true);ghost.className='drag-ghost';ghost.removeAttribute('draggable');document.body.appendChild(ghost);source.classList.add('dragging');let activeSlot=null;const move=e=>{ghost.style.left=`${e.clientX+12}px`;ghost.style.top=`${e.clientY+12}px`;const found=document.elementFromPoint(e.clientX,e.clientY)?.closest('.slot');if(activeSlot!==found){activeSlot?.classList.remove('dragover');activeSlot=found;if(activeSlot)activeSlot.classList.add('dragover')}};const finish=e=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',finish);activeSlot?.classList.remove('dragover');ghost.remove();source.classList.remove('dragging');const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.slot');if(!target)return;if(target.dataset.item!==item)return toast('Esse material nao pertence a este encaixe.');placeIngredient(item)};document.addEventListener('mousemove',move);document.addEventListener('mouseup',finish,{once:true});move(event)}
function renderInventory(filter=''){$('inventory').innerHTML=usableInventory(filter).map(i=>{const req=state.recipe.ingredients.find(x=>x.name===i.name),need=required(req),enough=i.count>=need,placed=state.placed.has(i.name);return `<div class="item ${enough?'draggable':'unavailable'} ${placed?'placed':''}" data-item="${esc(i.name)}"><img draggable="false" src="${image(i.name)}"><div><strong>${esc(i.label)}</strong><small>${enough?'Segure e arraste para o encaixe':`Faltam ${need-i.count} unidade(s)`}</small></div><b>${i.count}x</b></div>`}).join('')||'<p>Voce nao possui materiais utilizaveis.</p>';$('inventory').querySelectorAll('.item.draggable:not(.placed)').forEach(el=>el.addEventListener('mousedown',e=>startManualDrag(e,el)))}
function renderCatalog(){$('catalog').innerHTML=state.recipes.map(r=>`<button class="catalog-card" data-recipe="${esc(r.id)}"><img src="${image(r.item)}"><div><strong>${esc(r.label)}</strong><small>${esc(r.description||'Projeto de fabricacao')}</small><b>${r.ingredients.length} materiais</b></div></button>`).join('')||'<p>Nenhum craft configurado neste local.</p>';$('catalog').querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>selectRecipe(b.dataset.recipe))}
function showCatalog(){state.recipe=null;state.placed.clear();$('catalog').classList.remove('hidden');$('recipeDetail').classList.add('hidden');$('materialsPanel').classList.add('hidden');$('inventoryHint').classList.remove('hidden');$('search').value=''}
function updateAssembly(){if(!state.recipe)return;const total=state.recipe.ingredients.length,current=state.recipe.ingredients.filter(i=>state.placed.has(i.name)&&amount(i.name)>=required(i)).length,pct=total?Math.round(current/total*100):100;$('statusPct').textContent=pct+'%';$('statusBar').style.width=pct+'%';$('statusText').textContent=current===total?'Montagem pronta para fabricacao':`${current} de ${total} componentes validos`;$('craft').disabled=current!==total||state.busy;renderInventory($('search').value)}
function setupSlots(){$('slots').querySelectorAll('.slot').forEach(slot=>{slot.addEventListener('dragenter',e=>{e.preventDefault();slot.classList.add('dragover')});slot.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='move';slot.classList.add('dragover')});slot.addEventListener('dragleave',e=>{if(!slot.contains(e.relatedTarget))slot.classList.remove('dragover')});slot.addEventListener('drop',e=>{e.preventDefault();slot.classList.remove('dragover');const item=e.dataTransfer.getData('application/x-nv-crafting-item')||e.dataTransfer.getData('text/plain');if(item!==slot.dataset.item)return toast('Esse material nao pertence a este encaixe.');placeIngredient(item)});slot.querySelector('.remove-slot').onclick=e=>{e.stopPropagation();state.placed.delete(slot.dataset.item);slot.classList.remove('ok','filled','insufficient');slot.classList.add('missing');const ingredient=state.recipe.ingredients.find(x=>x.name===slot.dataset.item);slot.querySelector('small').textContent=`Arraste ${required(ingredient)}x para ca`;slot.querySelector('b').classList.add('hidden');slot.querySelector('.remove-slot').classList.add('hidden');updateAssembly()}})}
function selectRecipe(id,retained=[]){state.recipe=state.recipes.find(r=>r.id===id);if(!state.recipe)return;state.placed.clear();const r=state.recipe,q=quantity();$('quantity').value=q;$('catalog').classList.add('hidden');$('recipeDetail').classList.remove('hidden');$('materialsPanel').classList.remove('hidden');$('inventoryHint').classList.add('hidden');$('recipeName').textContent=r.label;$('requirementCount').textContent=`${r.ingredients.length} encaixes`;$('resultName').textContent=`${r.count*q}x ${r.label}`;$('resultDescription').textContent=r.description||'Resultado final do projeto';$('resultImage').src=image(r.item);$('footerImage').src=image(r.item);$('slots').innerHTML=r.ingredients.map(x=>{const need=required(x);return `<div class="slot missing" data-item="${esc(x.name)}"><img src="${image(x.name)}"><div><strong>${esc(x.label)}</strong><small>Arraste ${need}x para ca</small><b class="hidden"></b></div><button class="remove-slot hidden" aria-label="Remover">×</button></div>`}).join('');setupSlots();retained.forEach(item=>{const ingredient=r.ingredients.find(x=>x.name===item),slot=[...document.querySelectorAll('.slot')].find(el=>el.dataset.item===item);if(!ingredient||!slot)return;const enough=amount(item)>=required(ingredient);state.placed.add(item);slot.classList.remove('missing');slot.classList.add('filled',enough?'ok':'insufficient');slot.querySelector('small').textContent=enough?`${required(ingredient)}x posicionado`:`${amount(item)}/${required(ingredient)} - insuficiente`;slot.querySelector('b').textContent=`${required(ingredient)}x`;slot.querySelector('b').classList.remove('hidden');slot.querySelector('.remove-slot').classList.remove('hidden')});updateAssembly()}
function applyResult(result){state.inventory=result.inventory||state.inventory;state.outputs=result.outputs||state.outputs;renderOutputs();if(state.recipe)selectRecipe(state.recipe.id)}
async function takeOutput(id){if(state.busy)return;state.busy=true;renderOutputs();const result=await post('takeOutput',{id}).catch(()=>({ok:false,error:'Falha de comunicacao.'}));state.busy=false;if(!result.ok){toast(result.error||'Nao foi possivel retirar.');return renderOutputs()}applyResult(result)}
function open(data){Object.assign(state,{project:data.project,recipes:data.recipes||[],inventory:data.inventory||[],outputs:data.outputs||[],imagePath:data.imagePath||'',recipe:null});$('quantity').dataset.max=data.maxQuantity||50;$('quantity').value=1;$('title').textContent=data.project.label;$('app').classList.remove('hidden');renderCatalog();renderOutputs();showCatalog()}
function close(){$('app').classList.add('hidden');state.project=null;post('close')}
window.addEventListener('message',e=>{if(e.data.action==='open')open(e.data);if(e.data.action==='close'){$('app').classList.add('hidden');state.project=null}if(e.data.action==='progress'){const start=performance.now(),duration=e.data.duration||3000;state.progressTimer=requestAnimationFrame(function tick(now){const pct=Math.min(100,Math.round((now-start)/duration*100));$('statusText').textContent='Fabricando item...';$('statusPct').textContent=pct+'%';$('statusBar').style.width=pct+'%';if(pct<100)state.progressTimer=requestAnimationFrame(tick)})}if(e.data.action==='progressEnd')cancelAnimationFrame(state.progressTimer)});
$('close').onclick=close;$('back').onclick=showCatalog;$('search').oninput=e=>renderInventory(e.target.value);$('outputSearch').oninput=renderOutputs;$('quantity').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'')};$('quantity').onchange=()=>{if(state.recipe)selectRecipe(state.recipe.id,[...state.placed])};document.addEventListener('keyup',e=>{if(e.key==='Escape'&&state.recipe)return showCatalog();if(e.key==='Escape'&&state.project)close()});
$('craft').onclick=async()=>{const valid=state.recipe&&state.recipe.ingredients.every(i=>state.placed.has(i.name)&&amount(i.name)>=required(i));if(!valid||state.busy)return;state.busy=true;$('craft').disabled=true;const result=await post('craft',{recipe:state.recipe.id,quantity:quantity()}).catch(()=>({ok:false,error:'Falha de comunicacao.'}));state.busy=false;if(!result.ok){toast(result.error||'Nao foi possivel fabricar.');return selectRecipe(state.recipe.id,[...state.placed])}applyResult(result)};
$('takeAll').onclick=async()=>{if(state.busy||!state.outputs.length)return;state.busy=true;renderOutputs();const result=await post('takeAllOutputs').catch(()=>({ok:false,error:'Falha de comunicacao.'}));state.busy=false;if(!result.ok){toast(result.error||'Nao foi possivel retirar.');return renderOutputs()}applyResult(result);toast(`${result.taken||0} item(ns) retirado(s).`)};
setInterval(async()=>{if(!state.project||state.busy)return;const result=await post('refreshOutputs').catch(()=>null);if(result?.ok){state.outputs=result.outputs||[];renderOutputs()}},2000);
